name: npm publish

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: windows-latest
    container:
      image: node:14.16
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: publish
        working-directory: ../../
        run: npm publish
