name: npm publish

on:
  push:
    branches: [master]

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm publish
