name: npm publish

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: node:14.16
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/setup-node@master
      - working-directory: ./
      - run: npm install
      - run: npm publish
