name: npm publish

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Test
        run: dir
      - name: publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: ../../
        run: npm publish
