name: npm publish

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - run: npm install
      - run: npm publish
